
#-------------------
# Shared Metadata Model
# Object Property Configuration Settings
#-------------------
#
# This section defines every metadata property that can be used
# in the system. Individual work types may override some settings
# defined here. Predicates for each property should be defined
# here, and cannot be overridden once defined.

properties:

  # Example only:
  # default:
  #   usage_note: "Multiple instances are allowed, but discouraged. In some contexts it cannot be predicited which value will be displayed."
  #   sample_value: "The best property ever"
  #   controlled_values: #use vocabularies or list (not both)
  #      vocabularies: #connection to questioning authority?
  #          uri: http://uri.for.supported/vocabulary
  #          authority:
  #          sub-authority:
  #      list:  # or ref to config file list
  #         - value 1
  #         - value 2
  #         - value 3  #      
  #   validations: # Assumes that validations are something extensible, and we want to ship some of them, and have a conversation about what those extensions are # validator: RDF::LiteralValidator # Based on discussion, we are defering decision on whether we need this
  #      obligation: 0..n
  #   facet: #could this and search be simiplified somehow?
  #      faceted: #true/false
  #      facet_group: #facet group name
  #   search:
  #      search_indexed: #true/false
  #      search_group: #search group name
  #   display:
  #      display_label: "Label"     
  #      display_group: 
  #         - title
  #         - type
  #         - search_results
  #         - object
  #         - collection
  #      display_order: #ref to configuration file? #how best to express this? do we need to organize into concept groups? e.g., all the notes, all the agents?
  #      display_suppressed: #true/false (e.g., visible only to staff)
  
  
  title: # Property Name
    usage_note: "Preferrably, make the titles of resources unique within a collection. However, there is no hard rule against duplicate object titles."
    sample_value: "Sun God: decorated as Rambird, 1986: front view"
    validations: 
      obligation: 1
    facet: 
       faceted: false
    search:
       search_indexed: true
       search_group:  
          - title
          - all_fields
    display:
       display_label: "Title"
       display_group:
          - title
          - search_results
          - object
       display_order: 
       display_suppressed: false

  agent_creator: 
    usage_note: "Can be used when lacking specific information on an agent's exact role in creating the resource."
    validations: 
       obligation: 0..n
    facet:
       faceted: true
       facet_group: creators
    search:
       search_indexed: true
       search_group:
          - creators
          - all_fields
    display:
       display_label: "Creator" #is there a way to express that the field label should equal the prefLabel for the predicate?
       display_title: false
       display_type: false
       display_group:
          - object
          - search_results
       display_order: 
       display_suppressed: false

  
